### ISSUE TITLE
Criar sistema de pontuação

### ISSUE THREAD

**Issue by Jacobin939** [anotherlusitano/Aventuras-Pinguinasticas#2]
Fazer que a pontuação esteja no ficheiro

**Comment by anotherlusitano** [comment]
Criar dentro do construtor do Jogador as seguintes coisas:

Tarefas a serem feitas dentro do construtor do Jogador aka `public Jogador()`:
- Ler um ficheiro chamado `pontuacao.txt`, caso não existe, vai cria-lo com o valor zero lá dentro;
- Vai pegar o valor dentro do ficheiro, e vai associa-lo ao campo `pontuacao` do Jogador;

Tarefas a serem feitas dentro do setter do Jogador aka `public setPontuacao()`:
- Dentro do `setPontuacao` vai atualizar o valor da pontuacao no campo `pontuacao` e também vai salvar dentro do ficheiro `pontuacao.txt`
