### ISSUE TITLE
Guardar o nome do Jogador no ficheiro de pontuação

### ISSUE THREAD

**Issue by anotherlusitano** [anotherlusitano/Aventuras-Pinguinasticas#20]
Depois do #2 estiver feito, é para fazer as seguintes tarefas quando o jogo começar:

- Pedir o nome do utilizador;
- Criar jogador com esse nome + pontuação a zero;
- Fazer que guarde o nome do utilizador ao lado da pontuação, para identificar que aquela pontuação pertence àquele jogador;
- Refactorar a função de salvar/obter pontuação para que consiga salvar/obter a pontuação sem dar erro por causa do nome.

**Comment by Jacobin939** [comment]
Vai guardar no ficheiro pontuação:
nome | pontuação
`jogador1;100`
